# Generated by Django 4.2.4 on 2023-09-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('scriptsId', models.AutoField(primary_key=True, serialize=False)),
                ('scripts', models.TextField()),
            ],
        ),
    ]
